version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_RELAYER_URL=http://relayer:3001
      - NEXT_PUBLIC_RPC_ENDPOINT=https://api.devnet.solana.com
    depends_on:
      - relayer

  relayer:
    build:
      context: ./relayer
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - RPC_ENDPOINT=https://api.devnet.solana.com
      - RELAYER_PRIVATE_KEY=${RELAYER_PRIVATE_KEY}
      - JUPITER_API_KEY=${JUPITER_API_KEY}
    volumes:
      - ./relayer:/app
      - /app/node_modules
    depends_on:
      - zk-prover

  zk-prover:
    build:
      context: ./zk-coprocessor
      dockerfile: Dockerfile
    expose:
      - "50051"
    volumes:
      - ./zk-coprocessor:/app
      - /app/target

  validator:
    image: solanalabs/solana:v1.17.0
    ports:
      - "8899:8899"
      - "8900:8900"
    command: >
      solana-test-validator
      --reset
      --clone JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB
      --url https://api.devnet.solana.com
      --rpc-port 8899
      --bind-address 0.0.0.0 