[build]
  # Build command - install dependencies and prepare functions
  command = "npm install"
  
  # Directory to publish (for static files like swagger docs)
  publish = "public"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Environment variables for different contexts
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Headers for CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# API route redirects to serverless functions
[[redirects]]
  from = "/api/swap/quote"
  to = "/.netlify/functions/swap"
  status = 200

[[redirects]]
  from = "/api/swap/confirm"
  to = "/.netlify/functions/confirm"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# Legacy API redirects for backward compatibility
[[redirects]]
  from = "/api/swap"
  to = "/.netlify/functions/swap"
  status = 200

[[redirects]]
  from = "/api/confirm"
  to = "/.netlify/functions/confirm"
  status = 200

# Catch-all redirect for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Edge functions (none currently needed)
# [[edge_functions]]
#   path = "/example"
#   function = "example"

# Plugin configuration (removed Next.js plugin as this is a Node.js Express app)
# [[plugins]]
#   package = "@netlify/plugin-build-image" 